from django.db import models


class SafeJSONField(models.JSONField):
    """
    Custom JSONField to safely handle PostgreSQL JSONB values that psycopg driver
    has already deserialized into Python dict/list/etc.
    """
    def from_db_value(self, value, expression, connection):
        if value is None:
            return value
        if isinstance(value, (dict, list, int, float, bool)):
            return value
        try:
            return super().from_db_value(value, expression, connection)
        except TypeError:
            return value



class BaseFirewallLog(models.Model):
    """
    Abstract Django ORM Model for Cybersecurity Firewall Logs.
    Maps to existing PostgreSQL tables created and owned by FastAPI / SQLAlchemy.
    """
    id = models.AutoField(primary_key=True)
    log_date = models.DateTimeField(null=True, blank=True, db_index=True)
    ip_origin = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    ip_impacted = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    port_impacted = models.IntegerField(null=True, blank=True, db_index=True)
    zone_origin = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    zone_impacted = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    log_source = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    port_origin = models.IntegerField(null=True, blank=True, db_index=True)
    protocol = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    action = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    severity = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    threat_name = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    application = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    country_origin = models.CharField(max_length=100, null=True, blank=True)
    country_impacted = models.CharField(max_length=100, null=True, blank=True)
    rule_name = models.CharField(max_length=255, null=True, blank=True)
    classification = models.CharField(max_length=255, null=True, blank=True, db_index=True)
    additional_data = SafeJSONField(default=dict, null=True, blank=True)

    class Meta:
        abstract = True


class PaloAltoLog(BaseFirewallLog):
    """
    Django ORM model representing Palo Alto firewall logs.
    Set managed = False so Django never runs migrations or alters this table.
    """
    class Meta:
        managed = False
        db_table = "palo_alto_logs"
        ordering = ["-log_date"]
        verbose_name = "Palo Alto Log"
        verbose_name_plural = "Palo Alto Logs"


class FortinetLog(BaseFirewallLog):
    """
    Django ORM model representing Fortinet firewall logs.
    """
    class Meta:
        managed = False
        db_table = "fortinet_logs"
        ordering = ["-log_date"]
        verbose_name = "Fortinet Log"
        verbose_name_plural = "Fortinet Logs"


class FortiwafLog(BaseFirewallLog):
    """
    Django ORM model representing FortiWAF Web Application Firewall logs.
    """
    class Meta:
        managed = False
        db_table = "fortiwaf_logs"
        ordering = ["-log_date"]
        verbose_name = "FortiWAF Log"
        verbose_name_plural = "FortiWAF Logs"


class AIThreatAlert(models.Model):
    """
    Django ORM model representing AI Threat Predictions / Alerts (`prediction_logs`).
    Set managed = False so Django never alters the table managed by FastAPI / SQLAlchemy.
    Stores real-time predictions generated by CNN-LSTM (Label 1: Reconnaissance, Label 2: Lateral Movement, Label 3: Beaconing).
    """
    id = models.AutoField(primary_key=True)
    created_at = models.DateTimeField(null=True, blank=True, db_index=True)
    ip_origin = models.CharField(max_length=50, null=True, blank=True, db_index=True)
    label = models.IntegerField(db_index=True)  # 0: Normal, 1: Reconnaissance, 2: Lateral Movement, 3: Beaconing
    threat_name = models.CharField(max_length=100, null=True, blank=True, db_index=True)
    confidence_score = models.FloatField()
    sequence_metadata = SafeJSONField(default=dict, null=True, blank=True)

    class Meta:
        managed = False
        db_table = "prediction_logs"
        ordering = ["-created_at"]
        verbose_name = "AI Threat Alert"
        verbose_name_plural = "AI Threat Alerts"

    @property
    def risk_level(self):
        if self.label == 3:
            return "Critical"
        elif self.label in (1, 2):
            return "High"
        return "Normal"

    @property
    def risk_badge_class(self):
        if self.label == 3:
            return "bg-red-100 text-red-700 border border-red-300 animate-pulse"
        elif self.label in (1, 2):
            return "bg-orange-100 text-orange-700 border border-orange-300"
        return "bg-slate-100 text-slate-600 border border-slate-200"

